name: main

on: 
  push:
    branches: [main]

jobs:
   build:
       runs-on: ubuntu-latest

       permissions:
         contents: write

       steps:
        - name: Checkout repo
          uses: actions/checkout@va

        - name: Setup Python
          uses: actions/setup-python@v5
          with:
              python-version: '3.11'

        - name: Run script
          run: python ./Roadmap/stats.py

        - name: Commit and Push changes
          uses: stefanzweifel/git-auto-commit-action@v5
          with: 
             commit_message: Update stats
             commit_user_name: Brais Moure [GitHub Actions]
             commit_user_mail: maikenycm03@gmail.com
             commit_author: maikeny
