name: CI Pipeline

on: [push, pull_request]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with: { node-version: '18' }
      - run: npm install
      - run: npm test                # <— aquí corren tus pruebas unitarias

  integration-tests:
    needs: unit-tests             # espera que unit-tests pase
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:15
        env: { POSTGRES_PASSWORD: postgres }
        ports: ['5432:5432']
    steps:
      - uses: actions/checkout@v3
      - name: Setup DB
        run: |
          # configurar migraciones, seeders…
      - run: npm run test:integration  # <— pruebas de integración

  e2e-tests:
    needs: [unit-tests, integration-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm run test:e2e           # <— pruebas de extremo a extremo
